# This is a basic workflow to help you get started with Actions

name: Download And Archive Kick Livestream VOD

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  download-or-archive:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Cache For Downloaded Livestream
        id: restore-cache
        uses: actions/cache@v3.0.8
        with:
          # A list of files, directories, and wildcard patterns to cache and restore
          path: |
            *.mp4
            **/*.mp4
            *.mkv
            **/*.mkv
            *.ts
            **/*.ts
          # An explicit key for restoring and saving the cache
          key: stream-vod

      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"
          cache: "pip" # caching pip dependencies

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Download livestream
        env:
          XDG_DATA_HOME: ${{ github.workspace }}
        continue-on-error: true
        run: python download.py

      - name: Upload to archive
        id: upload-to-archive
        continue-on-error: true
        env:
          accesskey: ${{secrets.ACCESS_KEY}}
          secret: ${{secrets.SECRET}}
          bucketname: infrared-vods
        run: |
          file=$(find -type f -name "*.mp4" -or -type f -name "*.mkv" -or -type f -name "*.ts");
          fileName=${file:2}
          fileNameEncoded=$(python -c "import urllib.parse, sys; print(urllib.parse.quote(sys.argv[1]))"  "$fileName")
          echo $fileNameEncoded
          curl -g --location --header 'x-archive-queue-derive:0' --header 'x-amz-auto-make-bucket:1' --header "authorization: LOW $accesskey:$secret" --upload-file "$file" http://s3.us.archive.org/"$bucketname"/"$fileNameEncoded"

      - name: Delete Uploaded Files
        if: steps.upload-to-archive.outcome == 'success'
        run: |
          find -type f -name "*.mp4" -or -type f -name "*.mkv" -or -type f -name "*.ts" -delete
